### ISSUE TITLE
Add Ansible_Sync_CVP to Repo

### ISSUE THREAD

**Issue by Hugh-Adams** [aristanetworks/netdevops-examples#20]
In order to bring all Ansible Examples into the same place the Ansible_Sync_CVP repo (https://github.com/Hugh-Adams/Ansible_Sync_CVP) should be replicated into the netdevops-examples repo.

**Comment by titom73** [comment]
Hello @Hugh-Adams 

Please open an issue with your content added to `ansible/` directory.
We will run a review and merge it to the master branch shortly.

Thanks you !
